using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace MomoPetApp
{
    public partial class PetController
    {

        void BuildCompliancePanel()
        {
            compliancePanel=new Window{Title="博道咪合规审核",Width=Math.Max(900,SystemParameters.WorkArea.Width-28),Height=Math.Max(650,SystemParameters.WorkArea.Height-28),MinWidth=900,MinHeight=650,WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.CanResize,ShowInTaskbar=false,AllowsTransparency=true,Background=Brushes.Transparent,Topmost=pet.Topmost};Ui.StyleWindow(compliancePanel);var outer=new Border{CornerRadius=new CornerRadius(18),Padding=new Thickness(18)};Ui.StyleCard(outer);var rootGrid=new Grid();rootGrid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});rootGrid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});rootGrid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});rootGrid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
            var header=new Grid{Margin=new Thickness(2,0,0,16)};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var heading=new StackPanel();heading.Children.Add(Ui.Title("合规审核",22));heading.Children.Add(Ui.Subtitle("规则初筛  ·  模型语境复核  ·  人工确认  ·  审计留痕"));header.Children.Add(heading);var close=Ui.MakeCloseButton();close.Click+=delegate{compliancePanel.Hide();};Grid.SetColumn(close,1);header.Children.Add(close);rootGrid.Children.Add(header);AddShelfControl(compliancePanel,header,close);EnableWindowInteraction(compliancePanel,header);
            var top=new Grid{Margin=new Thickness(0,10,0,10)};top.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(2,GridUnitType.Star)});top.ColumnDefinitions.Add(new ColumnDefinition());top.ColumnDefinitions.Add(new ColumnDefinition());top.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var modelStack=new StackPanel();modelStack.Children.Add(new TextBlock{Text="审核模型",FontWeight=FontWeights.Bold});complianceModelBox=new ComboBox{Height=36,Margin=new Thickness(0,4,8,0),Padding=new Thickness(9,5,9,5),IsEditable=true,IsTextSearchEnabled=true,StaysOpenOnEdit=true,ItemsSource=ActiveTextModels()};complianceModelBox.Text=ActiveTextModel()??"";EnableModelSearch(complianceModelBox,delegate{return ActiveTextModels();});modelStack.Children.Add(complianceModelBox);top.Children.Add(modelStack);var reviewerStack=new StackPanel();reviewerStack.Children.Add(new TextBlock{Text="审核人员",FontWeight=FontWeights.Bold});complianceReviewerBox=new TextBox{Height=36,Margin=new Thickness(0,4,8,0),Padding=new Thickness(9,5,9,5),ToolTip="填写人工复核人员姓名或工号"};reviewerStack.Children.Add(complianceReviewerBox);Grid.SetColumn(reviewerStack,1);top.Children.Add(reviewerStack);var referenceStack=new StackPanel();referenceStack.Children.Add(new TextBlock{Text="引用位置",FontWeight=FontWeights.Bold});complianceReferenceBox=new TextBox{Height=36,Margin=new Thickness(0,4,8,0),Padding=new Thickness(9,5,9,5),ToolTip="页码、幻灯片编号、工作表或图片编号"};referenceStack.Children.Add(complianceReferenceBox);Grid.SetColumn(referenceStack,2);top.Children.Add(referenceStack);var settings=MakeButton("⚙ 模型设置",Ui.Neutral);settings.VerticalAlignment=VerticalAlignment.Bottom;settings.Click+=delegate{ShowImageAiSettings();};Grid.SetColumn(settings,3);top.Children.Add(settings);Grid.SetRow(top,1);rootGrid.Children.Add(top);
            var body=new Grid();body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(0.95,GridUnitType.Star)});body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1.35,GridUnitType.Star)});
            var resultPanel=new Grid{Margin=new Thickness(0,0,10,0)};resultPanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});resultPanel.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
            var complianceTabs=new Grid();complianceTabs.ColumnDefinitions.Add(new ColumnDefinition());complianceTabs.ColumnDefinitions.Add(new ColumnDefinition());
            complianceLocalTab=MakeButton("本地审核",Ui.AccentSoft);complianceLocalTab.Height=36;complianceLocalTab.Padding=new Thickness(4,5,4,5);complianceLocalTab.Margin=new Thickness(1);complianceLocalTab.FontSize=12.5;complianceLocalTab.ToolTip="词库扫描与模型合并后的命中清单，在此逐条人工处置";complianceLocalTab.Click+=delegate{ShowComplianceReviewTab(false);};complianceTabs.Children.Add(complianceLocalTab);
            complianceModelTab=MakeButton("AI 审核",Ui.Neutral);complianceModelTab.Height=36;complianceModelTab.Padding=new Thickness(4,5,4,5);complianceModelTab.Margin=new Thickness(1);complianceModelTab.FontSize=12.5;complianceModelTab.ToolTip="模型结合语境的复核结论原文，可选中复制";complianceModelTab.Click+=delegate{ShowComplianceReviewTab(true);};Grid.SetColumn(complianceModelTab,1);complianceTabs.Children.Add(complianceModelTab);
            resultPanel.Children.Add(new Border{Background=Ui.Inner,BorderBrush=Ui.Line,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(11),Padding=new Thickness(3),Margin=new Thickness(0,0,0,10),Child=complianceTabs});
            complianceLocalPanel=new Grid();complianceLocalPanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});complianceLocalPanel.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});complianceLocalPanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});complianceLocalPanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});Grid.SetRow(complianceLocalPanel,1);resultPanel.Children.Add(complianceLocalPanel);
            complianceSummary=new TextBlock{Text="尚未审核",FontWeight=FontWeights.Bold,Margin=new Thickness(2,0,2,8),TextWrapping=TextWrapping.Wrap};complianceLocalPanel.Children.Add(complianceSummary);complianceFindingList=new ListBox{BorderBrush=Ui.Line,BorderThickness=new Thickness(1),Background=Ui.Inner,SelectionMode=SelectionMode.Single,MinHeight=180};complianceFindingList.SelectionChanged+=delegate{ShowSelectedComplianceFinding();};Grid.SetRow(complianceFindingList,1);complianceLocalPanel.Children.Add(complianceFindingList);var disposition=new WrapPanel{Margin=new Thickness(0,8,0,8)};var confirm=MakeButton("确认问题",new SolidColorBrush(Color.FromRgb(255,222,184)));confirm.Click+=delegate{SetComplianceDisposition("确认问题");};var falsePositive=MakeButton("标为误报",new SolidColorBrush(Color.FromRgb(231,243,236)));falsePositive.Click+=delegate{SetComplianceDisposition("误报");};var accepted=MakeButton("采纳建议",Ui.Neutral);accepted.Click+=delegate{SetComplianceDisposition("已采纳建议");};disposition.Children.Add(confirm);disposition.Children.Add(falsePositive);disposition.Children.Add(accepted);Grid.SetRow(disposition,2);complianceLocalPanel.Children.Add(disposition);var detailBorder=new Border{Background=Ui.Inner,BorderBrush=Ui.Line,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Padding=new Thickness(10),MaxHeight=190};complianceFindingDetail=new TextBlock{Text="选择命中项查看规则编号、原因和修改建议",TextWrapping=TextWrapping.Wrap,Foreground=Ui.SubInk};detailBorder.Child=new ScrollViewer{Content=complianceFindingDetail,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};Grid.SetRow(detailBorder,3);complianceLocalPanel.Children.Add(detailBorder);
            complianceModelPanel=new Grid{Visibility=Visibility.Collapsed};complianceModelPanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});complianceModelPanel.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});Grid.SetRow(complianceModelPanel,1);resultPanel.Children.Add(complianceModelPanel);complianceModelPanel.Children.Add(new TextBlock{Text="模型结合语境的复核结论（可选中复制）",Foreground=Ui.SubInk,FontSize=11.5,Margin=new Thickness(2,0,2,6)});
            complianceResult=new TextBox{IsReadOnly=true,IsReadOnlyCaretVisible=true,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(8),Background=Ui.Inner,BorderBrush=Ui.Line,BorderThickness=new Thickness(1)};complianceResult.Text="尚未开始模型复核；点击下方“开始审核”后，这里会显示完整复核原文。";Grid.SetRow(complianceResult,1);complianceModelPanel.Children.Add(complianceResult);body.Children.Add(resultPanel);
            var sourcePanel=new Grid();sourcePanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});sourcePanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});sourcePanel.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});sourcePanel.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});complianceSource=new TextBlock{Text="输入或从中转袋带入待审核文本/文件",Foreground=Ui.SubInk,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(2,0,2,6)};sourcePanel.Children.Add(complianceSource);compliancePreview=new Image{Height=108,Stretch=System.Windows.Media.Stretch.Uniform,Visibility=Visibility.Collapsed,Margin=new Thickness(0,0,0,7)};Grid.SetRow(compliancePreview,1);sourcePanel.Children.Add(compliancePreview);complianceInput=new TextBox{AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(10),VerticalContentAlignment=VerticalAlignment.Top,MinHeight=170,ToolTip="支持粘贴文本，或从中转袋带入 Word/PPT/Excel/文本/图片"};complianceInput.TextChanged+=delegate{RunLocalComplianceScan();};Grid.SetRow(complianceInput,2);sourcePanel.Children.Add(complianceInput);complianceOriginalView=new RichTextBox{IsReadOnly=true,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(10),Background=Ui.Inner,BorderBrush=Ui.Line,BorderThickness=new Thickness(1),Visibility=Visibility.Collapsed,ToolTip="红/橙/黄色底色为命中内容；点击高亮项可回到左侧问题，悬停查看详情"};Grid.SetRow(complianceOriginalView,2);sourcePanel.Children.Add(complianceOriginalView);var sourceActions=new WrapPanel{Margin=new Thickness(0,8,0,0)};var import=MakeButton("带入中转所选",Ui.Neutral);import.Click+=delegate{OpenComplianceReview(SelectedStash());};var editOriginal=MakeButton("编辑原文",Ui.Neutral);editOriginal.Click+=delegate{ShowComplianceEditor();complianceInput.Focus();};var clearImage=MakeButton("移除图片",Brushes.Transparent);clearImage.Click+=delegate{SetComplianceImage(null);};sourceActions.Children.Add(import);sourceActions.Children.Add(editOriginal);sourceActions.Children.Add(clearImage);Grid.SetRow(sourceActions,3);sourcePanel.Children.Add(sourceActions);Grid.SetColumn(sourcePanel,1);body.Children.Add(sourcePanel);Grid.SetRow(body,2);rootGrid.Children.Add(body);
            var bottom=new Grid{Margin=new Thickness(0,11,0,0)};bottom.ColumnDefinitions.Add(new ColumnDefinition());bottom.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});bottom.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});bottom.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});complianceStatus=new TextBlock{Text="本地规则会先扫描；模型只负责结合语境解释和补充",Foreground=Ui.SubInk,VerticalAlignment=VerticalAlignment.Center,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(2,0,8,0)};bottom.Children.Add(complianceStatus);var history=MakeButton("审核记录",Ui.Neutral);history.Click+=delegate{ShowComplianceHistory();};Grid.SetColumn(history,1);bottom.Children.Add(history);var export=MakeButton("导出报告",Ui.Neutral);export.Click+=delegate{ExportComplianceReport();};Grid.SetColumn(export,2);bottom.Children.Add(export);var audit=MakeButton("开始审核",Ui.Accent);audit.Foreground=Brushes.White;audit.Click+=delegate{RunComplianceAudit();};Grid.SetColumn(audit,3);bottom.Children.Add(audit);Grid.SetRow(bottom,3);rootGrid.Children.Add(bottom);PolishComplianceLayout(rootGrid,top,body,resultPanel,sourcePanel,bottom);outer.Child=rootGrid;compliancePanel.Content=outer;compliancePanel.Closing+=delegate(object sender,System.ComponentModel.CancelEventArgs e){if(!exiting){e.Cancel=true;compliancePanel.Hide();}};
        }

        void PolishComplianceLayout(Grid rootGrid,Grid top,Grid body,Grid resultPanel,Grid sourcePanel,Grid bottom)
        {
            top.Margin=new Thickness(0);rootGrid.Children.Remove(top);var topCard=Ui.SurfacePanel(top,new Thickness(14,12,14,13),new Thickness(0,0,0,14));Grid.SetRow(topCard,1);rootGrid.Children.Add(topCard);
            body.Children.Remove(resultPanel);body.Children.Remove(sourcePanel);body.ColumnDefinitions.Clear();body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(.68,GridUnitType.Star),MinWidth=360});body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(10)});body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1.72,GridUnitType.Star),MinWidth=560});resultPanel.Margin=new Thickness(0);sourcePanel.Margin=new Thickness(0);var resultCard=Ui.SurfacePanel(resultPanel,new Thickness(14),new Thickness(0));var sourceCard=Ui.SurfacePanel(sourcePanel,new Thickness(14),new Thickness(0));Grid.SetColumn(sourceCard,2);var splitter=new GridSplitter{Width=3,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Stretch,Background=Ui.Line,ResizeBehavior=GridResizeBehavior.PreviousAndNext,ResizeDirection=GridResizeDirection.Columns,ToolTip="左右拖动，调整问题列表与原文区域宽度"};Grid.SetColumn(splitter,1);body.Children.Add(resultCard);body.Children.Add(splitter);body.Children.Add(sourceCard);
            complianceSummary.FontSize=13.5;complianceFindingList.Background=Ui.Card;complianceFindingList.BorderThickness=new Thickness(0);complianceFindingDetail.FontSize=12.5;complianceFindingDetail.LineHeight=20;complianceResult.Background=Ui.Inner;complianceOriginalView.Background=Ui.Card;complianceOriginalView.FontSize=14;complianceOriginalView.Document.FontFamily=new FontFamily("Microsoft YaHei UI");complianceOriginalView.Document.FontSize=14;complianceOriginalView.Document.LineHeight=24;
            bottom.Margin=new Thickness(2,14,0,0);
        }

        void SetComplianceImage(string path)
        {
            complianceImagePath=null;if(compliancePreview!=null){compliancePreview.Source=null;compliancePreview.Visibility=Visibility.Collapsed;}if(String.IsNullOrWhiteSpace(path)||!File.Exists(path)||!IsImageFile(path))return;try{var image=new BitmapImage();image.BeginInit();image.CacheOption=BitmapCacheOption.OnLoad;image.DecodePixelHeight=180;image.UriSource=new Uri(path);image.EndInit();image.Freeze();complianceImagePath=path;compliancePreview.Source=image;compliancePreview.Visibility=Visibility.Visible;}catch{}
        }

        void ShowComplianceEditor(){if(complianceOriginalView!=null)complianceOriginalView.Visibility=Visibility.Collapsed;if(complianceInput!=null)complianceInput.Visibility=Visibility.Visible;}

        void ShowComplianceReviewTab(bool model)
        {
            if(complianceLocalPanel==null||complianceModelPanel==null)return;
            complianceLocalPanel.Visibility=model?Visibility.Collapsed:Visibility.Visible;
            complianceModelPanel.Visibility=model?Visibility.Visible:Visibility.Collapsed;
            if(complianceLocalTab!=null)complianceLocalTab.Background=model?Ui.Neutral:Ui.AccentSoft;
            if(complianceModelTab!=null)complianceModelTab.Background=model?Ui.AccentSoft:Ui.Neutral;
        }

        void RunLocalComplianceScan()
        {
            if(complianceInput==null||complianceFindingList==null)return;currentComplianceFindings.Clear();currentComplianceCoveredFindings.Clear();currentComplianceFindings.AddRange(ScanComplianceRules(complianceInput.Text??""));RefreshComplianceFindings();
            if(complianceOriginalView!=null&&complianceOriginalView.Visibility==Visibility.Visible)RenderComplianceOriginal(complianceInput.Text??"");
        }

        void OpenComplianceReview(StashItem item=null)
        {
            if(compliancePanel==null)BuildCompliancePanel();if(RestoreShelvedIfNeeded(compliancePanel)){if(item==null)return;}if(complianceModelBox!=null){complianceModelBox.ItemsSource=null;complianceModelBox.ItemsSource=ActiveTextModels();complianceModelBox.Text=ActiveTextModel()??"";}if(item!=null){ShowComplianceEditor();complianceSourceName=item.Name??"中转资料";if(item.Kind=="image"&&File.Exists(item.Value)){complianceInput.Clear();SetComplianceImage(item.Value);complianceSource.Text="已带入图片："+complianceSourceName;complianceReferenceBox.Text="图片 1";}else{string reference;string extracted=ExtractStashPreviewText(item,out reference);complianceInput.Text=extracted;SetComplianceImage(null);complianceSource.Text="已带入中转资料："+complianceSourceName;complianceReferenceBox.Text=reference;}}if(!compliancePanel.IsVisible){var work=SystemParameters.WorkArea;compliancePanel.Width=Math.Max(900,work.Width-28);compliancePanel.Height=Math.Max(650,work.Height-28);compliancePanel.Left=work.Left+14;compliancePanel.Top=work.Top+14;compliancePanel.Show();}compliancePanel.Activate();if(item==null)complianceInput.Focus();RunLocalComplianceScan();if(item!=null&&item.Kind!="image"&&!String.IsNullOrWhiteSpace(complianceInput.Text))RenderComplianceOriginal(complianceInput.Text);
        }
}
}
